create table if not exists public.users (
    id bigint generated by default as identity primary key,
    username varchar(80) not null unique check (length(username) >= 3),
    email varchar(240) not null unique check (length(email) >= 5),
    full_name varchar(120) not null check (length(full_name) > 0),
    password_hash varchar(220) not null check (length(password_hash) > 0),
    monthly_income double precision not null default 0 check (monthly_income >= 0),
    savings_goal double precision not null default 0 check (savings_goal >= 0),
    preferred_currency varchar(8) not null default 'INR',
    created_at timestamptz not null default now()
);

create index if not exists idx_users_username on public.users (username);
create index if not exists idx_users_email on public.users (email);
create index if not exists idx_users_created_at on public.users (created_at desc);

alter table public.users enable row level security;

revoke all on table public.users from anon, authenticated;

alter table public.trips
    add column if not exists user_id bigint references public.users(id) on delete cascade;

alter table public.transactions
    add column if not exists user_id bigint references public.users(id) on delete cascade;

create index if not exists idx_trips_user_id on public.trips (user_id);
create index if not exists idx_transactions_user_id on public.transactions (user_id);
