create table if not exists public.transactions (
    id bigint generated by default as identity primary key,
    amount double precision not null check (amount > 0),
    description varchar(240) not null check (length(description) > 0),
    category varchar(80) not null check (length(category) > 0),
    merchant varchar(120) not null check (length(merchant) > 0),
    is_income boolean not null default false,
    date timestamptz not null default now()
);

create index if not exists idx_transactions_date on public.transactions (date desc);
create index if not exists idx_transactions_category on public.transactions (category);
create index if not exists idx_transactions_merchant on public.transactions (merchant);

alter table public.transactions enable row level security;

revoke all on table public.transactions from anon, authenticated;
