create table if not exists public.trips (
    id bigint generated by default as identity primary key,
    name varchar(120) not null check (length(name) > 0),
    destination varchar(120) not null check (length(destination) > 0),
    budget double precision not null default 0 check (budget >= 0),
    created_at timestamptz not null default now()
);

create index if not exists idx_trips_created_at on public.trips (created_at desc);
create index if not exists idx_trips_destination on public.trips (destination);

alter table public.trips enable row level security;

revoke all on table public.trips from anon, authenticated;
